CREATE TABLE posts (
    id INT PRIMARY KEY AUTO_INCREMENT,
    content TEXT NOT NULL,
    likes INT NOT NULL DEFAULT 0,
    liked BOOL NOT NULL DEFAULT FALSE,
    author JSON NOT NULL,
    removed BOOL NOT NULL DEFAULT FALSE,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    firstName TEXT NOT NULL,
    lastName TEXT NOT NULL,
    postsLiked JSON DEFAULT NULL ,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    myPosts JSON DEFAULT NULL
);